version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fractal
    ports:
      - "8030:8030"
    volumes:
      - ./app:/app
      - ./scripts:/app/scripts
      - ./data:/dbdata
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=${DATABASE_URL}
      - TEST_DATABASE_URL=${TEST_DATABASE_URL}
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8030 --reload

  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fractal_bot
    volumes:
      - ./app:/app
      - ./scripts:/app/scripts
      - ./data:/dbdata
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=${DATABASE_URL}
      - TEST_DATABASE_URL=${TEST_DATABASE_URL}
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      - db
    command: python -u -m telegram.hot_run_bot
    restart: always

  db:
    image: postgres:15
    container_name: fractal_db
    restart: always
    environment:
      POSTGRES_USER: fractal_user
      POSTGRES_PASSWORD: fractal_pass
      POSTGRES_DB: test_fractal_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
